url: bret.io
paginate: 10
permalink: pretty
markdown: rdiscount
safe: true
lsi: false
pygments: true
port: 4000
future: true
exclude: [categories.html, Gemfile, Gemfile.lock, README.md, vendor, cache.manifest]
include: [".well-known"]
permalink: pretty

source:      .
destination: ./_site
plugins:     ./_plugins

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      permalink: /:year/:month/:day/:title/

author: "Bret Comnes"
description: "A Personal Website and Blog"
location: "Portland, OR"
brand: "bret.io"  # This is displays in the navbar
permalink_marker: "&#916;"  # This is the permalink marker. 
linklog: "&#8620;"	# This is the little indicator next to link-log posts
ownyourgram: "/media/ownyourgram/"

recent_posts: 10

gems:
#- jekyll-mentions
- jemoji
- jekyll-redirect-from

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url: http://bret.io

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

# Prose stuff
prose:
  siteurl: http://bret.io
  #relativeLinks: 'http://bret.io/pages.jsonp'
  media: 'media'
  metadata:
    _posts/articles:
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date: YYYY-MM-DD HH:MM"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://bret.io/pages/tags.jsonp'
          alterable: true
    _posts/notes:
      - name: "layout"
        field:
          element: "hidden"
          value: "note"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date: YYYY-MM-DD HH:MM"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://bret.io/pages/tags.jsonp'
          alterable: true
      - name: "reply_url"
        field:
          element: "text"
          label: "Reply to URL"
      - name: "reply_title"
        field:
          element: "text"
          label: "Name of reply"
    _posts/linklog:
      - name: "layout"
        field:
          element: "hidden"
          value: "linklog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date: YYYY-MM-DD HH:MM"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://bret.io/pages/tags.jsonp'
          alterable: true
      - name: "external_url"
        field:
            element: "text"
            label: "Link"
